name: Minigames
description: Manage mini games
author: StarTux
version: 0.1
main: com.winthier.minigames.MinigamesPlugin
depend: [ ProtocolLib ]
softdepend: [ NoCheatPlus ]
database: true
commands:
  Minigames:
    aliases: [ Mini ]
    description: Admin interface
    permission: minigames.minigames
permissions:
  minigames.minigames:
    description: Use the "/minigames" command.
    default: op
